[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "openai>=3.20.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "requests>=2.34.2",
    "uvicorn>=0.54.0",
]
